config/routes.rb
Quickbalance::Application.routes.draw do
  get "transactions/new"

  get "transactions/index"

  get "transactions/show"

  get "pending_transactions/show"

  get "pending_transactions/new"

  get "pending_transactions/confirm"

  get "pending_transactions/index"

  get "accounts/new"

  get "accounts/create"

  get "accounts/show"

  get "accounts/index"

  devise_for :users

  get "pages/home"

  post "sms/create"

  resources :transactions
  resources :pending_transactions do
    member do
      patch 'confirm'
    end
  end
  resources :accounts

  root :to => 'pages#home'

end

app/controllers/pending_transactions_controller.rb
class PendingTransactionsController < ApplicationController
  rescue_from ActiveRecord::RecordInvalid, :with => :record_not_valid

  before_filter :authenticate_user!

  def show
  end

  def new
    @pending_transaction = current_user.pending_transactions.new
  end

  def confirm

    pending_transaction = PendingTransaction.find_by_id(params[:pending_transaction][:id])
    # check if the transaction's user id is the same as the one submitted...why??

    if ( pending_transaction.user_id == params[:pending_transaction][:user_id].to_i ) && pending_transaction.is_confirm_ready?
      # Successful confirm
      pending_transaction.confirm_transaction
      flash[:success] = "Successfully confirmed this pending transaction."
      
    else
      # failed confirm
      flash[:error] = "Something was wrong with confirming your pending transaction."

    end
    @pending_transactions = current_user.pending_transactions.all
    @transactions = current_user.transactions.all

  end

  def create
    @pending_transaction = current_user.pending_transactions.new(pending_transactions_params)
    if @pending_transaction.save
      @pending_transactions = current_user.pending_transactions.all(order: 'created_at DESC')
      @transaction = current_user.transactions.new(params[:transaction])
      
      @transactions = current_user.transactions.all(order: 'created_at DESC')

      flash[:success] = "Successfully created this pending transaction."

      respond_to do |format|
        format.js {
          render :create
        }
      end


      #redirect_to pages_home_path, :success => "Pending Transaction successfully created."
      
    else
      @pending_transactions = current_user.pending_transactions.all(order: 'created_at DESC')

     

      @transaction = current_user.transactions.new(params[:transaction])
      @transactions = current_user.transactions.all(order: 'created_at DESC')

      flash[:error] = "There was a problem with your pending transaction."

      respond_to do |format|
        format.js {
          render :create
        }
      end

      
      #render 'pages/home'
    end


  end


  def destroy
    @pending_transaction = PendingTransaction.find(params[:id])
    @pending_transaction.destroy
    flash[:success] = "Successfully removed pending transaction."
    @pending_transactions = current_user.pending_transactions.all
  end


  def index
    @pending_transaction = current_user.pending_transactions.new
    @pending_transactions = current_user.pending_transactions.all(order: 'created_at DESC')

  end

  private

  # def record_not_valid
  #   puts "IHOW DID I GET HERE??????"
  #   @pending_transaction = current_user.pending_transactions.new(pending_transactions_params)
  #   @pending_transactions = current_user.pending_transactions.all(order: 'created_at DESC')
  #   @transaction = current_user.transactions.new(params[:transaction])
  #   @transactions = current_user.transactions.all(order: 'created_at DESC')
  #   puts "Before the flash"
  #   flash[:error] = "Something was wrong with confirming your pending transaction."
  #   puts "after the flash"
  #   # render 'pages/home'
  #   puts "after home"

  # end

  def pending_transactions_params
    # attr_accessible :amount, :credited_id, :custom_credit, :custom_debit, :debited_id, :desecription, :shortcode, :user_id
    params.require(:pending_transaction).permit(:amount, :credited_id, :custom_credit, :custom_debit, :debited_id, :description, :shortcode, :user_id)
  end


end

app/helpers/pending_transactions_helper.rb
module PendingTransactionsHelper
end

app/views/pending_transactions/_pending_transactions_table.html.erb
<div id="pending-transactions-table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>From</th>
        <th>Amount</th>
        <th>To</th>
        <!-- <th>Description</th> we can add in description later once we figure out inline editng...!-->
        <th>Date</th>
        <th>Shortcode</th>
        <th>Confirm</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% pending_transactions.each do |pending_transaction| %>
      <tr>
        <td><%= pending_transaction.debited ? link_to(pending_transaction.debited.name, pending_transaction.debited) : pending_transaction.custom_debit %></td>
        <td><%= number_to_currency(pending_transaction.amount) %></td>
        <td><%= pending_transaction.credited ? link_to(pending_transaction.credited.name, pending_transaction.credited) : pending_transaction.custom_credit %></td>
        <!-- <td><%= pending_transaction.description %></td> !-->
        <td><%= pending_transaction.created_at.stamp("January 1, 2011 at 12:23 PM") %></td>
        <td><%= pending_transaction.shortcode %></td>
        <td>
          <%= form_for(pending_transaction, :as => :pending_transaction, :url => confirm_pending_transaction_path(pending_transaction), :method => :patch, :remote => true) do |f| %>
          <%= f.hidden_field :id %>
          <%= f.hidden_field :user_id %>
          <%= f.submit "Confirm", class: 'btn btn-info' %>
          <% end %>
        </td>
        <td>
          <%= button_to "Remove", pending_transaction, :remote => true, data: {confirm: 'Are you sure you want to remove this pending transaction?' }, :class => "btn btn-danger", :method => :delete %>
        </td>



      </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/pending_transactions/_shorthand_pending_transaction_form.html.erb
<div class="input-group">
  <%= pending_transaction_form.text_field :shortcode, class: 'form-control input-lg', placeholder: "Enter a shortcode transaction here." %>
  <span class="input-group-btn"><%= pending_transaction_form.submit "Create Pending", class: 'btn btn-lg btn-success' %></span>

</div>
<span class="help-block">For example, "<%= current_user.accounts.first.debit_shorthand %> 100 <%= current_user.accounts.last.credit_shorthand %>" means moving $100 from your <%= current_user.accounts.first.name %> account to your <%= current_user.accounts.last.name %> account. Note this is <strong>case sensitive</strong>.</span>

app/views/pending_transactions/confirm.html.erb
<h1>PendingTransactions#confirm</h1>
<p>Find me in app/views/pending_transactions/confirm.html.erb</p>

app/views/pending_transactions/confirm.js.erb
$('#flash-area').html("<%= j(render partial: 'shared/flash_messages') %>");

$("#pending-transactions-table").html("<%= escape_javascript( render(:partial => "pending_transactions/pending_transactions_table", :locals => {:pending_transactions => @pending_transactions}) ) %>").fadeIn('slow');
$("#transactions-table").html("<%= escape_javascript( render(:partial => "transactions/transactions_table", :locals => {:transactions => @transactions}) ) %>").fadeIn('slow');

app/views/pending_transactions/create.js.erb

$('#flash-area').html("<%= j(render partial: 'shared/flash_messages') %>");

$(".data-shorthand-transaction-form")[0].reset(); // clears the shorthand form
$("#pending-transactions-table").html("<%= escape_javascript( render(:partial => "pending_transactions/pending_transactions_table", :locals => {:pending_transactions => @pending_transactions}) ) %>").fadeIn('slow');

app/views/pending_transactions/destroy.js.erb
$('#flash-area').html("<%= j(render partial: 'shared/flash_messages') %>");

$("#pending-transactions-table").html("<%= escape_javascript( render(:partial => "pending_transactions/pending_transactions_table", :locals => {:pending_transactions => @pending_transactions}) ) %>").fadeIn('slow');

app/views/pending_transactions/index.html.erb
<div class="row">
  <div class="col-mod-12">

    <h1>Pending Transactions</h1>

    <%= form_for(@pending_transaction) do |pending_transaction_form| %>

    <%= render 'shared/error_messages', :object =>pending_transaction_form.object %>
    
    <fieldset>
      <legend>Transaction Information</legend>

      Shortcode: <%= pending_transaction_form.text_field :shortcode %>

      
    </fieldset>
    
    <%= pending_transaction_form.submit "Create Pending Transaction" %>
    <% end %>


    <table>
      <thead>
        <tr>
          <th>From</th>
          <th>Amount</th>
          <th>To</th>
          <th>Description</th>
          <th>Date</th>
          <th>Shortcode</th>
        </tr>
      </thead>
      <tbody>
        <% @pending_transactions.each do |pending_transaction| %>
        <tr>
          <td><%= pending_transaction.debitted ? link_to(pending_transaction.debitted.name, pending_transaction.debitted) : pending_transaction.custom_debit %></td>
          <td><%= pending_transaction.amount %></td>
          
          <td><%= pending_transaction.credited ? link_to(pending_transaction.credited.name, pending_transaction.credited) : pending_transaction.custom_credit %></td>
          <td><%= pending_transaction.description %></td>
          <td><%= pending_transaction.created_at.stamp("January 1, 2011 at 12:23 PM") %></td>
          <td><%= pending_transaction.shortcode %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/pending_transactions/new.html.erb
<div class="row">
  <div class="col-md-12">

    <h1>New Pending Transaction</h1>

    <%= form_for(@pending_transaction) do |pending_transaction_form| %>

    <%= render 'shared/error_messages', :object =>pending_transaction_form.object %>

    <fieldset>
      <legend>Transaction Information</legend>

      Shortcode: <%= pending_transaction_form.text_field :shortcode %>


    </fieldset>

    <%= pending_transaction_form.submit "Create Pending Transaction" %>
    <% end %>
  </div>
</div>