config/routes.rb
Quickbalance::Application.routes.draw do
  get "transactions/new"

  get "transactions/index"

  get "transactions/show"

  get "pending_transactions/show"

  get "pending_transactions/new"

  get "pending_transactions/confirm"

  get "pending_transactions/index"

  get "accounts/new"

  get "accounts/create"

  get "accounts/show"

  get "accounts/index"

  devise_for :users

  get "pages/home"

  post "sms/create"

  resources :transactions
  resources :pending_transactions do
    member do
      patch 'confirm'
    end
  end
  resources :accounts

  root :to => 'pages#home'

end

app/views/layouts/_all_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">Quick Balance</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    </ul>



    <%= form_for("user", :html => { :class => "navbar-form navbar-right form-inline" }, :url => user_session_path) do |f| %>

    <div class="form-group">
      <%= f.text_field :email, :class => "form-control", :placeholder => "E-mail" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
    </div>

    <%= f.submit 'Login', :class => "btn btn-default"%>

    
    <% end %>




  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">Quick Balance</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Dashboard', pages_home_path %></li>



      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accounts <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% current_user.accounts.each do |account| %>
          <li><%= link_to account.name, account %></li>
          <% end %>
          <li class="divider"></li>
          <li><%= link_to 'All Accounts', accounts_path %></li>
        </ul>
      </li>

    </ul>



    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
    </ul>



  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quickbalance</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br />

  <div class="container">
    


    <% if user_signed_in? %>
    <!-- render user nav bar !-->
    <%= render 'layouts/user_navbar' %>

    <% else %>
    <%= render 'layouts/all_navbar' %>

    <% end %>


    <%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %>

    <%= yield %>

    <br /><hr /><br />
    <%= debug(params) if Rails.env.development? %>
    
  </div>




</body>
</html>